In [14]:
import pandas as pd

In [15]:
# #importing each table as a df to check dtypes
# game_plays_df = pd.read_csv('Resources/data/game_plays.csv')
# game_df = pd.read_csv('Resources/data/game.csv')
# game_plays_players_df = pd.read_csv('Resources/data/game_plays_players.csv')
# game_teams_stats_df = pd.read_csv('Resources/data/game_teams_stats.csv')
# game_shifts_df = pd.read_csv('Resources/data/game_shifts.csv')
# player_info_df = pd.read_csv('Resources/data/player_info.csv')
# game_skater_stats_df = pd.read_csv('Resources/data/game_skater_stats.csv')
# game_goalie_stats_df = pd.read_csv('Resources/data/game_goalie_stats.csv')
# team_info_df = pd.read_csv('Resources/data/team_info.csv')
# game_officials_df = pd.read_csv('Resources/data/game_officials.csv')
# game_goals_df = pd.read_csv('Resources/data/game_goals.csv')
# game_penalties_df = pd.read_csv('Resources/data/game_penalties.csv')
# game_scratches_df = pd.read_csv('Resources/data/game_scratches.csv')

In [16]:
# game_plays_df.dtypes
# game_df.dtypes
# game_plays_players_df.dtypes
# game_teams_stats_df.dtypes
# game_shifts_df.dtypes
# player_info_df.dtypes
# game_skater_stats_df.dtypes
# game_goalie_stats_df.dtypes
# team_info_df.dtypes
# game_officials_df.dtypes
# game_goals_df.dtypes
# game_penalties_df.dtypes
# game_scratches_df.dtypes

In [17]:
game_teams_stats_df = pd.read_csv('Resources/game_teams_stats.csv')
game_df = pd.read_csv('Resources/game.csv')
team_df = pd.read_csv('Resources/team_info.csv')

In [18]:
game_teams_stats_df

,game_id,team_id,HoA,won,settled_in,head_coach,goals,shots,hits,pim,powerPlayOpportunities,powerPlayGoals,faceOffWinPercentage,giveaways,takeaways,blocked,startRinkSide
0,2016020045,4,away,False,REG,Dave Hakstol,4.0,27.0,30.0,6.0,4.0,2.0,50.9,12.0,9.0,11.0,left
1,2016020045,16,home,True,REG,Joel Quenneville,7.0,28.0,20.0,8.0,3.0,2.0,49.1,16.0,8.0,9.0,left
2,2017020812,24,away,True,OT,Randy Carlyle,4.0,34.0,16.0,6.0,3.0,1.0,43.8,7.0,4.0,14.0,right
3,2017020812,7,home,False,OT,Phil Housley,3.0,33.0,17.0,8.0,2.0,1.0,56.2,5.0,6.0,14.0,right
4,2015020314,21,away,True,REG,Patrick Roy,4.0,29.0,17.0,9.0,3.0,1.0,45.7,13.0,5.0,20.0,left
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52605,2018030416,19,home,False,REG,Craig Berube,1.0,29.0,29.0,20.0,4.0,0.0,58.7,12.0,11.0,9.0,right
52606,2018030417,19,away,True,REG,Craig Berube,4.0,20.0,36.0,2.0,0.0,0.0,49.0,7.0,8.0,21.0,right
52607,2018030417,6,home,False,REG,Bruce Cassidy,1.0,33.0,28.0,0.0,1.0,0.0,51.0,13.0,6.0,7.0,right
52608,2018030417,19,away,True,REG,Craig Berube,4.0,20.0,36.0,2.0,0.0,0.0,49.0,7.0,8.0,21.0,right
52609,2018030417,6,home,False,REG,Bruce Cassidy,1.0,33.0,28.0,0.0,1.0,0.0,51.0,13.0,6.0,7.0,right

In [19]:
game_df

,game_id,season,type,date_time_GMT,away_team_id,home_team_id,away_goals,home_goals,outcome,home_rink_side_start,venue,venue_link,venue_time_zone_id,venue_time_zone_offset,venue_time_zone_tz
0,2016020045,20162017,R,2016-10-19T00:30:00Z,4,16,4,7,home win REG,right,United Center,/api/v1/venues/null,America/Chicago,-5,CDT
1,2017020812,20172018,R,2018-02-07T00:00:00Z,24,7,4,3,away win OT,left,KeyBank Center,/api/v1/venues/null,America/New_York,-4,EDT
2,2015020314,20152016,R,2015-11-24T01:00:00Z,21,52,4,1,away win REG,right,MTS Centre,/api/v1/venues/null,America/Winnipeg,-5,CDT
3,2015020849,20152016,R,2016-02-17T00:00:00Z,52,12,1,2,home win REG,right,PNC Arena,/api/v1/venues/null,America/New_York,-4,EDT
4,2017020586,20172018,R,2017-12-30T03:00:00Z,20,24,1,2,home win REG,left,Honda Center,/api/v1/venues/null,America/Los_Angeles,-7,PDT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26300,2018030415,20182019,P,2019-06-07T00:00:00Z,19,6,2,1,away win REG,left,TD Garden,/api/v1/venues/5085,America/New_York,-5,EST
26301,2018030416,20182019,P,2019-06-10T00:00:00Z,6,19,5,1,away win REG,left,Enterprise Center,/api/v1/venues/5076,America/Chicago,-6,CST
26302,2018030416,20182019,P,2019-06-10T00:00:00Z,6,19,5,1,away win REG,left,Enterprise Center,/api/v1/venues/5076,America/Chicago,-6,CST
26303,2018030417,20182019,P,2019-06-13T00:00:00Z,19,6,4,1,away win REG,left,TD Garden,/api/v1/venues/5085,America/New_York,-5,EST
26304,2018030417,20182019,P,2019-06-13T00:00:00Z,19,6,4,1,away win REG,left,TD Garden,/api/v1/venues/5085,America/New_York,-5,EST

In [21]:
team_df

,team_id,franchiseId,shortName,teamName,abbreviation,link
0,1,23,New Jersey,Devils,NJD,/api/v1/teams/1
1,4,16,Philadelphia,Flyers,PHI,/api/v1/teams/4
2,26,14,Los Angeles,Kings,LAK,/api/v1/teams/26
3,14,31,Tampa Bay,Lightning,TBL,/api/v1/teams/14
4,6,6,Boston,Bruins,BOS,/api/v1/teams/6
5,3,10,NY Rangers,Rangers,NYR,/api/v1/teams/3
6,5,17,Pittsburgh,Penguins,PIT,/api/v1/teams/5
7,17,12,Detroit,Red Wings,DET,/api/v1/teams/17
8,28,29,San Jose,Sharks,SJS,/api/v1/teams/28
9,18,34,Nashville,Predators,NSH,/api/v1/teams/18
10,23,20,Vancouver,Canucks,VAN,/api/v1/teams/23
11,16,11,Chicago,Blackhawks,CHI,/api/v1/teams/16
12,9,30,Ottawa,Senators,OTT,/api/v1/teams/9
13,8,1,Montreal,Canadiens,MTL,/api/v1/teams/8
14,30,37,Minnesota,Wild,MIN,/api/v1/teams/30
15,15,24,Washington,Capitals,WSH,/api/v1/teams/15
16,19,18,St Louis,Blues,STL,/api/v1/teams/19
17,24,32,Anaheim,Ducks,ANA,/api/v1/teams/24
18,27,28,Phoenix,Coyotes,PHX,/api/v1/teams/27
19,2,22,NY Islanders,Islanders,NYI,/api/v1/teams/2
20,10,5,Toronto,Maple Leafs,TOR,/api/v1/teams/10
21,13,33,Florida,Panthers,FLA,/api/v1/teams/13
22,7,19,Buffalo,Sabres,BUF,/api/v1/teams/7
23,20,21,Calgary,Flames,CGY,/api/v1/teams/20
24,21,27,Colorado,Avalanche,COL,/api/v1/teams/21
25,25,15,Dallas,Stars,DAL,/api/v1/teams/25
26,29,36,Columbus,Blue Jackets,CBJ,/api/v1/teams/29
27,52,35,Winnipeg,Jets,WPG,/api/v1/teams/52
28,22,25,Edmonton,Oilers,EDM,/api/v1/teams/22
29,54,38,Vegas,Golden Knights,VGK,/api/v1/teams/54
30,12,26,Carolina,Hurricanes,CAR,/api/v1/teams/12
31,53,28,Arizona,Coyotes,ARI,/api/v1/teams/53
32,11,35,Atlanta,Thrashers,ATL,/api/v1/teams/11